trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'src/BlazorNavigationManagerExtensions/BlazorNavigationManagerExtensions.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/BlazorNavigationManagerExtensions/BlazorNavigationManagerExtensions.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts'